// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSfoB6DpyiRR0e5CjgiutN0AqQv2JD44',
    appId: '1:303448519859:web:9c199430f208aac381ecc6',
    messagingSenderId: '303448519859',
    projectId: 'reservas-nativos',
    authDomain: 'reservas-nativos.firebaseapp.com',
    storageBucket: 'reservas-nativos.firebasestorage.app',
    measurementId: 'G-01BFPJ0Z8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1VSpAAFyW-1Q9csk692BxTW3QsgoaG_A',
    appId: '1:303448519859:android:acc5da04b73f1f8581ecc6',
    messagingSenderId: '303448519859',
    projectId: 'reservas-nativos',
    storageBucket: 'reservas-nativos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8mGMF_L-Y-aeXghWp01t3EPylbQbKSk',
    appId: '1:303448519859:ios:b5e9c9de0cff14c581ecc6',
    messagingSenderId: '303448519859',
    projectId: 'reservas-nativos',
    storageBucket: 'reservas-nativos.firebasestorage.app',
    iosBundleId: 'com.example.reservasNativos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA8mGMF_L-Y-aeXghWp01t3EPylbQbKSk',
    appId: '1:303448519859:ios:b5e9c9de0cff14c581ecc6',
    messagingSenderId: '303448519859',
    projectId: 'reservas-nativos',
    storageBucket: 'reservas-nativos.firebasestorage.app',
    iosBundleId: 'com.example.reservasNativos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChSfoB6DpyiRR0e5CjgiutN0AqQv2JD44',
    appId: '1:303448519859:web:103288742d930b9181ecc6',
    messagingSenderId: '303448519859',
    projectId: 'reservas-nativos',
    authDomain: 'reservas-nativos.firebaseapp.com',
    storageBucket: 'reservas-nativos.firebasestorage.app',
    measurementId: 'G-5TJ5L7B763',
  );
}
